name: advent_of_code
description: Solutions of the Advent of Code puzzles by Maurits van Beusekom
repository: https://github.com/mvanbeusekom/advent_of_code
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  equatable: ^2.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0